name: Android Release CI

on:
  release:
    types: [published, created]

jobs:
  apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
      - name: Upload fdroid artifact
        uses: actions/upload-artifact@v2
        with:
          name: Amaze-Fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
      - name: Upload play artifact
        uses: actions/upload-artifact@v2
        with:
          name: Amaze-Play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk
