name: Android Debug artifact ondemand

on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
  issue_comment:
    types: [created, edited]

jobs:
  apk:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'Build artifact' && github.actor == 'VishalNehra' || github.actor == 'TranceLove' || github.actor == 'EmmanuelMess'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          echo Run on-demand by ${GITHUB_ACTOR}
          bash ./gradlew assembleDebug --stacktrace
      - name: Upload fdroid artifact
        uses: actions/upload-artifact@v2
        with:
          name: Amaze-Fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
      - name: Upload play artifact
        uses: actions/upload-artifact@v2
        with:
          name: Amaze-Play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk